name: Build & Deploy NestJS via dist/

on:
  push:
    branches:
      - testdeploy-2

env:
  DROPLET_TARGET_PATH: /opt/deploy_artifacts
  # PM2 process name you use on the server
  PM2_PROCESS_NAME: artshare-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) install & build
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build dist/
        run: yarn build

      # 3) load your SSH key
      - name: Setup SSH agent
        run: |
          # start the agent
          eval "$(ssh-agent -s)"
          # write your private key into a file
          printf '%s\n' "${{ secrets.SSHKEY }}" > key.pem
          chmod 600 key.pem
          # add it to the agent, feeding the passphrase
          ssh-add key.pem <<< "${{ secrets.SSH_KEY_PASSPHRASE }}"
        shell: bash

      # 4) rsync the dist folder (preserves .env and other files)
      - name: Sync dist/ to droplet
        run: |
          rsync -avz --delete \
            --exclude='.env*' \
            ./dist/ \
            ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:${{ env.DROPLET_TARGET_PATH }}/dist/

      # 5) restart your Node service via PM2
      - name: Reload app on droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: 22
          script: |
            echo "→ Restarting $PM2_PROCESS_NAME via PM2"
            pm2 reload $PM2_PROCESS_NAME || pm2 start dist/src/main.js --name $PM2_PROCESS_NAME
