name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - testdeploy

env:
  REGISTRY: registry.digitalocean.com/artshare-be
  IMAGE_NAME: artshare-backend
  CONTAINER_NAME: artshare-app
  DROPLET_PORT: 3000  # change if your app runs on a different port

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login $REGISTRY -u doctl --password-stdin

      - name: Build Docker image
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker image to DOCR
        run: docker push $REGISTRY/$IMAGE_NAME:latest

      - name: SSH into Droplet and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            docker login $REGISTRY -u doctl --password ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            docker pull $REGISTRY/$IMAGE_NAME:latest
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker run -d \
              --name $CONTAINER_NAME \
              -p 80:${{ env.DROPLET_PORT }} \
              -e DATABASE_URL="${{ secrets.DATABASE_URL_SECRET }}" \
              -e API_KEY="${{ secrets.API_KEY_SECRET }}" \
              -e NODE_ENV="production" \ # It's good practice to explicitly set this
              # Add more -e flags for any other secrets/env vars your app needs
              $REGISTRY/$IMAGE_NAME:latest